# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12so5TUdrA17KRXZ7dsQN133tgZB-oAYs
"""

print("Se estará usando el lenguaje python")